import { slugifyName } from "@/lib/utils";

export type ParsedManagerMappingRow = {
  employeeName: string;
  employeeExternalId: string | null;
  managerName: string | null;
  employeeStatus: string | null;
  role: string | null;
  type: string | null;
  department: string | null;
  matchKey: string;
};

export function parseManagerMappingCsv(text: string) {
  const lines = text.split(/\r?\n/).map((line) => line.trimEnd());
  const rows: ParsedManagerMappingRow[] = [];
  let currentManager: string | null = null;

  for (const line of lines) {
    if (!line) {
      continue;
    }

    const columns = splitCsvLine(line);

    if (columns[0] === "Manager" && columns[1]) {
      currentManager = cleanCell(columns[1]);
      continue;
    }

    if (columns[0] === "Subtotal") {
      continue;
    }

    if (columns[1] === "Employee Name" || columns[0].startsWith("Report:") || columns[0].startsWith("Grouped By:") || columns[0].startsWith("Sorted By:") || columns[0].startsWith("Filtered By:") || columns[0].startsWith("Date & Time:") || columns[0].startsWith("Generated By:") || columns[0].startsWith("Company:")) {
      continue;
    }

    if (!columns[1]) {
      continue;
    }

    const employeeName = cleanCell(columns[1]);
    rows.push({
      employeeName,
      employeeExternalId: cleanCell(columns[8]) || null,
      managerName: currentManager,
      employeeStatus: cleanCell(columns[4]) || null,
      role: cleanCell(columns[2]) || null,
      type: cleanCell(columns[3]) || null,
      department: cleanCell(columns[2]) || null,
      matchKey: cleanCell(columns[8]) || slugifyName(employeeName)
    });
  }

  return rows;
}

function splitCsvLine(line: string) {
  const result: string[] = [];
  let current = "";
  let insideQuotes = false;

  for (let index = 0; index < line.length; index += 1) {
    const char = line[index];

    if (char === "\"") {
      insideQuotes = !insideQuotes;
      continue;
    }

    if (char === "," && !insideQuotes) {
      result.push(current);
      current = "";
      continue;
    }

    current += char;
  }

  result.push(current);
  return result;
}

function cleanCell(value: string | undefined) {
  return value?.replace(/^"+|"+$/g, "").trim() ?? "";
}
